name: books
favicon: null
layout_spectrum: 0.7576700821518898
typography_spectrum: 0.7699276192579418
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-60100244
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.588479237165302
purpose: []
